version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env
    hostname: ${POSTGRES_HOST}
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    container_name: birthdaybuddy-node
    build:
      context: .
      target: builder
    ports:
      - '3000:3000'
    volumes:
      - .:/birthdaybuddy
      - /birthdaybuddy/node_modules
    command: yarn start:migrate
    depends_on:
      - db
    restart: always
    env_file:
      - .env

volumes:
  db:
    driver: local
